policy_name: "Aug01_18-27-22_go2_pact_100hz_spec_smartcurr_stricterer.pt"
dt: 0.01
command_limit_max_abs: [1.0, 0.5, 1.0]  # [linear_x m/s, linear_y m/s, angular_z rad/s]
lowstate_timeout_ms: 100

use_kalman_filter: true
estimator_dt: 0.01
imu_process_noise_position: 0.02
imu_process_noise_velocity: 0.02
foot_process_noise_position: 0.002
foot_sensor_noise_position: 0.001
foot_sensor_noise_velocity: 0.1
foot_height_sensor_noise: 0.001
foot_force_contact_threshold: 15.0
go2_body_length: 0.3868
go2_body_width: 0.093
go2_abad_link_length: 0.0955
go2_hip_link_length: 0.213
go2_knee_link_length: 0.213

log_flush_count: 500
log_loop_dt: 0.05

stand_kp: 60.0
stand_kd: 5.0
ctrl_kp: 30.0
ctrl_kd: 0.6

pos_action_scale: 0.25
tau_action_scale: 10.0

lin_vel_scale: 1.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05

clip_observations: 100.0
clip_actions: 50.0
frame_stack: 20
num_single_obs: 57

stand_pos: [-0.1, 0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 0.95, -1.5, 0.1, 0.95, -1.5]

sit_pos: [0.04, 1.3, -2.70, -0.02, 1.29, -2.70, -0.33, 1.27, -2.70, 0.32, 1.28, -2.70]

joint_limit_max: [1.0472, 3.4907, -0.83776, 1.0472, 3.4907, -0.83776, 1.0472, 4.5379, -0.83776, 1.0472, 4.5379, -0.83776]
joint_limit_min: [-1.0472, -1.5708, -2.7227, -1.0472, -1.5708, -2.7227, -1.0472, -0.5236, -2.7227, -1.0472, -0.5236, -2.7227]
joint_tau_max: [23.7, 23.7, 45.43, 23.7, 23.7, 45.43, 23.7, 23.7, 45.43, 23.7, 23.7, 45.43]
